### ISSUE TITLE
can't create a map of non-copyable value

### ISSUE THREAD

**Issue by martinus** [Tessil/robin-map#10]
In my benchmark I use this data structure as a value:

```
struct BigData {
	std::shared_ptr<int> a;
	std::map<int, int> b;
	std::vector<double> c;
	std::unique_ptr<int> d;
	std::fstream f;
};
```

Using `tsl::robin_map<int, BigData>` gives this compile error:

```
src/maps/06_tsl/robin_hash.h:157:13: error: use of deleted function ‘constexpr std::pair<_T1, _T2>::pair(const std::pair<_T1, _T2>&) [with _T1 = int; _T2 = std::basic_fstream<char>]’
             ::new (static_cast<void*>(std::addressof(m_value))) value_type(other.value());
             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

**Comment by Tessil** [comment]
Hello,

Thank you for the report. Could you try the [fix_issue_10](https://github.com/Tessil/robin-map/tree/fix_issue_10) branch?

The problem seems to arise from the fact that `std::fstream` has a throwable move-constructor as move-only objects like `std::unique_ptr` and `std::shared_ptr` are supported well. 

It seems that `std::vector::resize` tries to use the copy constructor of `bucket_entry` but it shouldn't as it must use `default-inserted` elements. I have to investigate further on the reason as the solution in the branch isn't compatible with C++11 and I'd like to keep the compatibility.

**Comment by martinus** [comment]
Hi, I've tried the branch and it works for me, thanks!

**Comment by Tessil** [comment]
I merged the changes.
