### ISSUE TITLE
No matching function swap() when using robin_map::emplace()

### ISSUE THREAD

**Issue by MarkoPaul0** [Tessil/robin-map#19]
Hello, @Tessil,

I might be missing something in the documentation but I figured I would ping you on this. Basing my work on the few differences between the robin_map and the unordered_map, I don't understand why the following code does not compile:

```cpp
#include <unordered_map>
#include "external/tsl/robin_map.h"

struct SomeStruct {
  int val_;

  SomeStruct() : val_(0) {  }
  SomeStruct(int val) : val_(val) {  }
  SomeStruct& operator=(const SomeStruct&) = delete; // Comment this out and it compiles
};

int main(int argc, char *argv[]) {
  std::unordered_map<int, SomeStruct> unordered_map;
  unordered_map.emplace(std::piecewise_construct, std::forward_as_tuple(1), std::forward_as_tuple());

  tsl::robin_map<int, SomeStruct> robin_map;
  robin_map.emplace(std::piecewise_construct, std::forward_as_tuple(1), std::forward_as_tuple());
}
```

I get the following error:
```
error: no matching function for call to ‘swap(SomeStruct&, SomeStruct&)’
  swap(second, __p.second);
```

Keeping the assignment operator by not explicitly deleting it gets rid of the issue but I want to have it disabled. Any idea why emplace would need it in the robin_map?

(Also, I am using C++ 11)

Thanks in advance! :)

**Comment by Tessil** [comment]
Hello,

Thank you for the report. 

The problem comes from the fact that by deleting the copy assignment operator, you also disable the implicit move constructor and move operator which in turn makes the type not swappable by default.

The copy constructor and copy operator are not required but the used types must be swappable. They must also be copy and/or move constructible. I added this information in the README and the API. 

It isn't possible with robin hood hashing and open-addressing to avoid this as on insertion we sometime have to 'steal' the bucket of an already present value and move the value of the 'stolen' bucket further away.

**Comment by MarkoPaul0** [comment]
@Tessil,

Thank you for the explanation and thank you for creating this project 👍.
