### ISSUE TITLE
Using omp with robin-map

### ISSUE THREAD

**Issue by jowong4** [Tessil/robin-map#22]
I'm trying to do some operation on every key-value pair via omp

```
#pragma omp parallel for
for (const auto& itr : robin_map<key, hash>) {
    //some operation
}
```
and I'm getting this error

```error: no match for ‘operator-’ (operand types are ‘tsl::robin_map<long unsigned int, short unsigned int, fastHash>::iterator’ {aka ‘tsl::detail_robin_hash::robin_hash<std::pair<long unsigned int, short unsigned int>, tsl::robin_map<long unsigned int, short unsigned int, fastHash>::KeySelect, tsl::robin_map<long unsigned int, short unsigned int, fastHash>::ValueSelect, fastHash, std::equal_to<long unsigned int>, std::allocator<std::pair<long unsigned int, short unsigned int> >, false, tsl::rh::power_of_two_growth_policy<2> >::robin_iterator<false>’} and ‘tsl::robin_map<long unsigned int, short unsigned int, fastHash>::iterator’ {aka ‘tsl::detail_robin_hash::robin_hash<std::pair<long unsigned int, short unsigned int>, tsl::robin_map<long unsigned int, short unsigned int, fastHash>::KeySelect, tsl::robin_map<long unsigned int, short unsigned int, fastHash>::ValueSelect, fastHash, std::equal_to<long unsigned int>, std::allocator<std::pair<long unsigned int, short unsigned int> >, false, tsl::rh::power_of_two_growth_policy<2> >::robin_iterator<false>’}) ```

omp uses `operator-` to  find the number of jobs it has to do. Can you implement the operator overload?

**Comment by Tessil** [comment]
OpenMP requires a `RandomAccessIterator` but the iterator of `tsl::robin_map` is a `ForwardIterator`. Providing the `operator-(iterator, iterator)` method would be quite difficult without extra bookkeeping (and thus extra memory). 

Couldn't you use the method described in https://stackoverflow.com/questions/26034642/openmp-gnu-parallel-for-an-unordered-map/26038269#26038269? 

Otherwise [`tsl-ordered-map`](https://github.com/Tessil/ordered-map) provides a `RandomAccessIterator` but it'll be slower than `tsl-robin-map`.
