### ISSUE TITLE
robin_map and Poco

### ISSUE THREAD

**Issue by xumepoc** [Tessil/robin-map#30]
Hi,
After updating my Poco library (https://github.com/pocoproject) from version 1.9.0. to 1.9.4. I got errors mi my project for tsl:robin_map.h. I was able to fix them by adding:
#undef min in robin_hash.h 
and
#undef max in robin_growth_policy.h

I guess something changed in Poco, which was defining the min and max.

I am not sure if you need to change that in the tsl:robim-map project, I am just let you know about that behaviour :D 

P.S. I love your robin-map 😄

**Comment by Tessil** [comment]
Hi,

Than you very much for the report. 

I'm not really keen to add undef of external macros in the library. I think it should be better for the Poco library to avoid creating macros that conflict with the standard library in their header files, though it's probably due to the `windows.h` header of Windows. Could you try to define the [`NOMINMAX`](https://stackoverflow.com/questions/11544073/how-do-i-deal-with-the-max-macro-in-windows-h-colliding-with-max-in-std) macro instead of the undef?

Thibaut

**Comment by xumepoc** [comment]
Hi,
Unfortunately it did not do the trick, but I am also using a library which also uses Poco, so my case is a bit more specific. 
In a general use case I think I will work.

Todor
