### ISSUE TITLE
find/insert return iterators with read-only second element

### ISSUE THREAD

**Issue by lyskov** [Tessil/robin-map#56]
Dear Author(s), I am getting the following compilation error when trying to modify map-value when using iterators returned by `find`/`insert`. Is this expected behavior? Thanks,

Error: `error: assignment of member 'std::pair<int, int>::second' in read-only object`
Minimal code to reproduce:
```C++
tsl::robin_map<int, int> mp;
mp[0] = 0;
mp.find(0)->second = 1;
mp.insert({0, 1}).first->second = 2;
```

**Comment by Tessil** [comment]
Hi,

Yes it is a design choice. See point 5 on https://github.com/Tessil/robin-map#differences-compared-to-stdunordered_map

The map stores `std::pair<int, int>` values instead of `std::pair<const int, int>` that `std::unordered_map`. Returning a mutable reference would allow the modification of the key, it's why a const reference is returned instead and the `value()` method must be used.

**Comment by lyskov** [comment]
Got it, - thank you for clarification!

**Comment by jeremyong** [comment]
@Tessil can you elaborate on this a bit? In the case of a `robin_map`, I don't see why you wouldn't want to be able to mutate the value (not wanting to mutate the key is obvious). The interface as-is requires you to assign values entirely, as opposed to modifying portions of it.
